language: node_js
node_js:
  - "8"
  - "10"
cache: yarn
before_script:
  - yarn
script:
  - yarn lint
  - yarn cover
after_success:
  - npm install -g coveralls
  - cat coverage/lcov.info | coveralls
