os:
  - linux
  - osx
language: node_js
node_js:
  - '16'
cache: yarn
before_script:
  - yarn
  - git config --global user.email "travis-backport@travis-ci.org"
  - git config --global user.name "Travis Backport"
script:
  - yarn tsc
  - yarn eslint './**/*.{ts,js}'
  - 'if [ -n "$accessToken" ]; then echo "Running public and private tests" && yarn test --coverage && yarn test-private; fi'
  - 'if [ -z "$accessToken" ]; then echo "Running only public tests (excluding private ones) " && yarn test; fi'
after_success:
  - npm install -g coveralls
  - cat coverage/lcov.info | coveralls
