os:
  - linux
  - osx
addons:
  apt:
    sources:
      - ppa:git-core/ppa
    packages:
      - git
language: node_js
node_js:
  - '10'
  - '12'
cache: yarn
before_script:
  - yarn
script:
  - yarn lint
  - yarn cover
after_success:
  - npm install -g coveralls
  - cat coverage/lcov.info | coveralls
