os:
  - linux
  - osx
addons:
  apt:
    sources:
      - ppa:git-core/ppa
    packages:
      - git
language: node_js
node_js:
  - '10'
  - '12'
cache: yarn
before_script:
  - yarn
  - git config --global user.email "travis-backport@travis-ci.org"
  - git config --global user.name "Travis Backport"
script:
  - yarn tsc
  - yarn lint # lint ts and eslint
  - yarn jest --coverage # run tests and publish coverage
after_success:
  - npm install -g coveralls
  - cat coverage/lcov.info | coveralls
